# **Language Model Auto-complete in NLP**

# **Mounting the drive**

In [ ]:
from google.colab import drive
drive.mount('/content/drive')


Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


# **Load and Print Data**

In [ ]:
def load_data(file_path):
    with open(file_path, 'r', encoding='utf-8') as file:
        data = file.read()
    return data

# Example usage:
file_path = '/content/drive/MyDrive/NLP Project/twitter.txt'  # Update with actual file path
data = load_data(file_path)
print(data[:500])  # Print the first 500 characters to examine the data


How are you? Btw thanks for the RT. You gonna be in DC anytime soon? Love to see you. Been way, way too long.
When you meet someone special... you'll know. Your heart will beat more rapidly and you'll smile for no reason.
they've decided its more fun if I don't.
So Tired D; Played Lazer Tag & Ran A LOT D; Ughh Going To Sleep Like In 5 Minutes ;)
Words from a complete stranger! Made my birthday even better :)
First Cubs game ever! Wrigley field is gorgeous. This is perfect. Go Cubs Go!
i no! i ge


# **Split to Sentences**

In [ ]:
def split_to_sentences(data):
    sentences = data.split('\n')
    return sentences


# Example usage:
sentences = split_to_sentences(data)
print(sentences[:5])  # Print the first 5 sentences to check


['How are you? Btw thanks for the RT. You gonna be in DC anytime soon? Love to see you. Been way, way too long.', "When you meet someone special... you'll know. Your heart will beat more rapidly and you'll smile for no reason.", "they've decided its more fun if I don't.", 'So Tired D; Played Lazer Tag & Ran A LOT D; Ughh Going To Sleep Like In 5 Minutes ;)', 'Words from a complete stranger! Made my birthday even better :)']


# **Tokenize Sentences**

In [ ]:
import nltk
nltk.download('punkt')

def tokenize_sentences(sentences):
    tokenized_sentences = [nltk.word_tokenize(sentence.lower()) for sentence in sentences]
    return tokenized_sentences

# Example usage:
tokenized_sentences = tokenize_sentences(sentences)
print(tokenized_sentences[:5])  # Print the first 5 tokenized sentences to check


[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


[['how', 'are', 'you', '?', 'btw', 'thanks', 'for', 'the', 'rt', '.', 'you', 'gon', 'na', 'be', 'in', 'dc', 'anytime', 'soon', '?', 'love', 'to', 'see', 'you', '.', 'been', 'way', ',', 'way', 'too', 'long', '.'], ['when', 'you', 'meet', 'someone', 'special', '...', 'you', "'ll", 'know', '.', 'your', 'heart', 'will', 'beat', 'more', 'rapidly', 'and', 'you', "'ll", 'smile', 'for', 'no', 'reason', '.'], ['they', "'ve", 'decided', 'its', 'more', 'fun', 'if', 'i', 'do', "n't", '.'], ['so', 'tired', 'd', ';', 'played', 'lazer', 'tag', '&', 'ran', 'a', 'lot', 'd', ';', 'ughh', 'going', 'to', 'sleep', 'like', 'in', '5', 'minutes', ';', ')'], ['words', 'from', 'a', 'complete', 'stranger', '!', 'made', 'my', 'birthday', 'even', 'better', ':', ')']]


# **Tokenize Data**

In [ ]:
def tokenize_data(data):
    sentences = data.split('\n')
    tokenized_sentences = [nltk.word_tokenize(sentence.lower()) for sentence in sentences]
    return tokenized_sentences

# Example usage:
tokenized_data = tokenize_data(data)
print(tokenized_data[:5])  # Print the first 5 tokenized sentences to check


[['how', 'are', 'you', '?', 'btw', 'thanks', 'for', 'the', 'rt', '.', 'you', 'gon', 'na', 'be', 'in', 'dc', 'anytime', 'soon', '?', 'love', 'to', 'see', 'you', '.', 'been', 'way', ',', 'way', 'too', 'long', '.'], ['when', 'you', 'meet', 'someone', 'special', '...', 'you', "'ll", 'know', '.', 'your', 'heart', 'will', 'beat', 'more', 'rapidly', 'and', 'you', "'ll", 'smile', 'for', 'no', 'reason', '.'], ['they', "'ve", 'decided', 'its', 'more', 'fun', 'if', 'i', 'do', "n't", '.'], ['so', 'tired', 'd', ';', 'played', 'lazer', 'tag', '&', 'ran', 'a', 'lot', 'd', ';', 'ughh', 'going', 'to', 'sleep', 'like', 'in', '5', 'minutes', ';', ')'], ['words', 'from', 'a', 'complete', 'stranger', '!', 'made', 'my', 'birthday', 'even', 'better', ':', ')']]


# **Train/Test Split**

In [ ]:
from sklearn.model_selection import train_test_split

def train_test_split_data(tokenized_data, test_size=0.2):
    train_data, test_data = train_test_split(tokenized_data, test_size=test_size, random_state=42)
    return train_data, test_data

# Example usage:
train_data, test_data = train_test_split_data(tokenized_data)
print(f"Train size: {len(train_data)}, Test size: {len(test_data)}")
print('\n\n', test_data)

Train size: 38369, Test size: 9593


 [['the', 'industry', 'keeps', 'seeking', 'ways', 'to', 'circumvent', 'the', 'fickle', 'power', 'of', 'pure', 'creativity', '.', 'but', 'nothing', "'s", 'beat', 'it', 'yet', '.'], ['perfect', 'for', 'easter', '!', 'thanks', '...', 'd'], ['we', "'re", 'about', 'to', 'blow', 'your', 'feed', 'up', ',', 'brace', 'yourselves', '...', '<', '3'], ['rt', 'if', 'you', "'re", 'happy', 'for', 'austin', 'because', 'he', "'s", 'living', 'his', 'dream', '<', '3'], ['ha', ',', 'eric', ',', 'you', '&', 'joyce', 'r', 'the', 'rock', 'stars', '!', 'actually', ',', 'i', 'think', 'i', "'ve", 'seen', 'pics', 'of', 'you', 'in', 'a', 'feather', 'boa', '!', ';', ')'], ['todays', 'mvp', 'for', 'the', 'falcons', 'should', 'be', 'roddy', 'white', '.', 'great', 'job', 'knocking', 'the', 'ball', 'lose', 'in', 'the', '4th', 'quarter', '.'], ['the', 'inconsistency', 'in', 'his', 'rulings', 'are', 'inexplicable', '.', 'like', 'it', 'says', 'in', 'the', 'article', ',', 'seems', 'lik

# **Count Words**

In [ ]:
from collections import Counter

def count_words(tokenized_data):
    word_counts = Counter(word for sentence in tokenized_data for word in sentence)
    return word_counts

# Example usage:
word_counts = count_words(train_data)
print(word_counts.most_common(10))  # Print the 10 most common words


[('.', 23617), ('!', 20865), ('the', 15213), ('i', 14796), ('to', 12706), (',', 12272), ('a', 9892), ('you', 9818), ('and', 7082), ('?', 6793)]


# **Words with N frequency**

In [ ]:
def get_closed_vocabulary(word_counts, threshold):
    closed_vocab = {word for word, count in word_counts.items() if count >= threshold}
    return closed_vocab

# Example usage:
threshold = 5
closed_vocab = get_closed_vocabulary(word_counts, threshold)
print(f"Closed vocabulary size: {len(closed_vocab)}")


Closed vocabulary size: 6834


# **Replace OOV with UNK**

In [ ]:
def replace_oov_with_unk(tokenized_data, closed_vocab, unk_token='<unk>'):
    replaced_data = [[word if word in closed_vocab else unk_token for word in sentence] for sentence in tokenized_data]
    return replaced_data

# Example usage:
replaced_train_data = replace_oov_with_unk(train_data, closed_vocab)
replaced_test_data = replace_oov_with_unk(test_data, closed_vocab)
print(replaced_train_data[:5])  # Print the first 5 replaced tokenized sentences to check


[['where', 'are', 'you', '<unk>', '?'], ['that', "'s", 'right', 'you', 'will', '!', ':', ')', 'rt', ':', 'silly', 'class', 'u', '<unk>', 'me', 'from', 'winning', 'tt', '.', 'but', 'ill', 'get', 'them', 'next', 'time'], ['#', 'nowplaying', '``', '<unk>', "'s", '<unk>', "''", ',', '<unk>', 'clark'], ['looking', 'forward', 'to', 'it', '!', 'xo'], ['fuck', 'you', 'romantic', '<unk>', '.', 'fuck', '.', 'you', '.']]


# **Preprocess Data**

In [ ]:
def preprocess_data(data, threshold, test_size=0.2):
    sentences = split_to_sentences(data)
    tokenized_sentences = tokenize_sentences(sentences)
    train_data, test_data = train_test_split_data(tokenized_sentences, test_size)
    word_counts = count_words(train_data)
    closed_vocab = get_closed_vocabulary(word_counts, threshold)
    train_data_replaced = replace_oov_with_unk(train_data, closed_vocab)
    test_data_replaced = replace_oov_with_unk(test_data, closed_vocab)
    return train_data_replaced, test_data_replaced, closed_vocab

# Example usage:
threshold = 5
train_data_processed, test_data_processed, vocab = preprocess_data(data, threshold)
print(f"Processed train size: {len(train_data_processed)}, Processed test size: {len(test_data_processed)}")


Processed train size: 38369, Processed test size: 9593


In [ ]:
type(vocab)

set

# **Count N Grams**

In [ ]:
from collections import defaultdict

def count_ngrams(data, n):
    ngrams = defaultdict(int)
    for sentence in data:
        sentence = ['<s>'] * (n-1) + sentence + ['<e>']
        for i in range(len(sentence) - n + 1):
            ngram = tuple(sentence[i:i+n])
            ngrams[ngram] += 1
    return ngrams

# Example usage:
n = 2
bigrams = count_ngrams(train_data_processed, n)
print(list(bigrams.items())[:10])  # Print the first 10 bigrams to check


[(('<s>', 'where'), 95), (('where', 'are'), 36), (('are', 'you'), 370), (('you', '<unk>'), 223), (('<unk>', '?'), 870), (('?', '<e>'), 3017), (('<s>', 'that'), 404), (('that', "'s"), 562), (("'s", 'right'), 15), (('right', 'you'), 1)]


# **Estimate Probability of Single Word**

In [ ]:
def estimate_probability(word, previous_ngram, ngram_counts, nplus1gram_counts, vocab_size, k=1):
    previous_ngram = tuple(previous_ngram)
    previous_ngram_count = ngram_counts.get(previous_ngram, 0)
    nplus1gram = previous_ngram + (word,)
    nplus1gram_count = nplus1gram_counts.get(nplus1gram, 0)
    probability = (nplus1gram_count + k) / (previous_ngram_count + k * vocab_size)
    return probability

# Example usage:
vocab_size = len(vocab) + 1  # Include <unk>
previous_ngram = ['i', 'eat']
word = 'scrambled'
probability = estimate_probability(word, previous_ngram, bigrams, count_ngrams(train_data_processed, 3), vocab_size)
print(f"Probability of '{word}' given '{previous_ngram}': {probability}")


Probability of 'scrambled' given '['i', 'eat']': 0.00014609203798392987


# **Estimate Probability of all Words**

In [ ]:
def estimate_probabilities(previous_ngram, ngram_counts, nplus1gram_counts, vocab, k=1):
    vocab_size = len(vocab) + 1  # Include <unk>
    probabilities = {}
    for word in vocab:
        probabilities[word] = estimate_probability(word, previous_ngram, ngram_counts, nplus1gram_counts, vocab_size, k)
    return probabilities

# Example usage:
previous_ngram = ['i', 'eat']
vocab = closed_vocab | {'<unk>'}
probabilities = estimate_probabilities(previous_ngram, bigrams, count_ngrams(train_data_processed, 3), vocab)
print(list(probabilities.items())[:10])  # Print the probabilities for the first 10 words to check


[('brings', 0.00014607069821793748), ('100th', 0.00014607069821793748), ('weeding', 0.00014607069821793748), ('producer', 0.00014607069821793748), ('mon', 0.00014607069821793748), ('dignity', 0.00014607069821793748), ('injuries', 0.00014607069821793748), ('scent', 0.00014607069821793748), ('b4', 0.00014607069821793748), ('contract', 0.00014607069821793748)]


# **Make Count Matrix**

In [ ]:
import numpy as np

def make_count_matrix(nplus1gram_counts, vocab):
    vocab = list(vocab)
    vocab_size = len(vocab)
    count_matrix = np.zeros((vocab_size, vocab_size))
    vocab_to_index = {word: idx for idx, word in enumerate(vocab)}

    for (ngram, count) in nplus1gram_counts.items():
        if len(ngram) == 2:  # Assuming bigrams
            prev_word, next_word = ngram
            if prev_word in vocab_to_index and next_word in vocab_to_index:
                prev_word_idx = vocab_to_index[prev_word]
                next_word_idx = vocab_to_index[next_word]
                count_matrix[prev_word_idx, next_word_idx] = count

    return count_matrix

# Example usage:
vocab = closed_vocab | {'<unk>'}
count_matrix = make_count_matrix(count_ngrams(train_data_processed, 2), vocab)
print(count_matrix)


[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


# **Calculate Perplexity**

In [ ]:
def calculate_perplexity(sentence, ngram_counts, nplus1gram_counts, vocab_size, k=1):
    sentence = ['<s>'] * (len(ngram_counts) - 1) + sentence + ['<e>']
    N = len(sentence)
    log_prob_sum = 0
    for i in range(len(sentence) - len(ngram_counts) + 1):
        ngram = tuple(sentence[i:i+len(ngram_counts)])
        nplus1gram = tuple(sentence[i:i+len(ngram_counts)+1])
        log_prob_sum += np.log2(estimate_probability(nplus1gram[-1], ngram, ngram_counts, nplus1gram_counts, vocab_size, k))
    perplexity = 2**(-log_prob_sum / N)
    return perplexity

# Example usage:
sentence = ['i', 'eat', 'scrambled', 'eggs']
perplexity = calculate_perplexity(sentence, bigrams, count_ngrams(train_data_processed, 3), vocab_size)
print(f"Perplexity of the sentence '{' '.join(sentence)}': {perplexity}")


Perplexity of the sentence 'i eat scrambled eggs': 1.0002512195769684


# **Suggest a Word**

In [ ]:
def suggest_a_word(previous_tokens, ngram_counts, nplus1gram_counts, vocab, k=1, start_with=None):
    vocab_size = len(vocab) + 1  # Include <unk>
    probabilities = estimate_probabilities(previous_tokens, ngram_counts, nplus1gram_counts, vocab, k)
    if start_with:
        filtered_probabilities = {word: prob for word, prob in probabilities.items() if word.startswith(start_with)}
    else:
        filtered_probabilities = probabilities
    suggested_word = max(filtered_probabilities, key=filtered_probabilities.get)
    return suggested_word, filtered_probabilities[suggested_word]

# Example usage:
previous_tokens = ['i', 'eat', 'scrambled']
suggested_word, max_probability = suggest_a_word(previous_tokens, bigrams, count_ngrams(train_data_processed, 3), vocab)
print(f"Suggested word: {suggested_word}, Max probability: {max_probability}")


Suggested word: brings, Max probability: 0.0001462843768285547


# **Get Suggestions**

In [ ]:
def get_suggestions(previous_tokens, ngram_counts_list, vocab, k=1, start_with=None):
    suggestions = []
    vocab = list(vocab) + ['<unk>']

    for n in range(1, len(ngram_counts_list) + 1):
        ngram_counts = ngram_counts_list[n-1]
        previous_ngram = tuple(previous_tokens[-(n-1):])
        nplus1gram_counts = count_ngrams(train_data_processed, n+1)
        probabilities = estimate_probabilities(previous_ngram, ngram_counts, nplus1gram_counts, vocab, k)

        for word, prob in probabilities.items():
            if start_with and not word.startswith(start_with):
                continue
            suggestions.append((word, prob))

    suggestions.sort(key=lambda x: x[1], reverse=True)
    return suggestions[:5]  # Return top 5 suggestions

# Example usage:
previous_tokens = ['i', 'eat', 'scrambled']
suggestions = get_suggestions(previous_tokens, [count_ngrams(train_data_processed, n) for n in range(1, 7)], closed_vocab, k=1)
print(f"Suggestions: {suggestions}")


Suggestions: [('100th', 0.0001462843768285547), ('dignity', 0.0001462843768285547), ('contract', 0.0001462843768285547), ('closing', 0.0001462843768285547), ('nyu', 0.0001462843768285547)]


# **Testing**

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

def load_data(file_path):
    with open(file_path, 'r', encoding='utf-8') as file:
        data = file.read()
    return data

file_path = '/content/drive/MyDrive/NLP Project/twitter.txt'
data = load_data(file_path)
print(data[:500])

def split_to_sentences(data):
    sentences = data.split('\n')
    return sentences

sentences = split_to_sentences(data)
print(sentences[:5])

import nltk
nltk.download('punkt')

def tokenize_sentences(sentences):
    tokenized_sentences = [nltk.word_tokenize(sentence.lower()) for sentence in sentences]
    return tokenized_sentences

tokenized_sentences = tokenize_sentences(sentences)
print(tokenized_sentences[:5])

from sklearn.model_selection import train_test_split

def train_test_split_data(tokenized_sentences, test_size=0.2):
    train_data, test_data = train_test_split(tokenized_sentences, test_size=test_size, random_state=42)
    return train_data, test_data

train_data, test_data = train_test_split_data(tokenized_sentences)
print(f"Train size: {len(train_data)}, Test size: {len(test_data)}")

from collections import Counter

def count_words(tokenized_sentences):
    word_counts = Counter(word for sentence in tokenized_sentences for word in sentence)
    return word_counts

word_counts = count_words(train_data)
print(word_counts.most_common(10))

def get_closed_vocabulary(word_counts, threshold):
    closed_vocab = {word for word, count in word_counts.items() if count >= threshold}
    return closed_vocab

threshold = 5
closed_vocab = get_closed_vocabulary(word_counts, threshold)
print(f"Closed vocabulary size: {len(closed_vocab)}")

def replace_oov_with_unk(tokenized_sentences, closed_vocab, unk_token='<unk>'):
    replaced_sentences = [[word if word in closed_vocab else unk_token for word in sentence] for sentence in tokenized_sentences]
    return replaced_sentences

train_data_replaced = replace_oov_with_unk(train_data, closed_vocab)
test_data_replaced = replace_oov_with_unk(test_data, closed_vocab)
print(train_data_replaced[:5])

from collections import defaultdict

def count_ngrams(data, n):
    ngrams = defaultdict(int)
    for sentence in data:
        sentence = ['<s>'] * (n-1) + sentence + ['<e>']
        for i in range(len(sentence) - n + 1):
            ngram = tuple(sentence[i:i+n])
            ngrams[ngram] += 1
    return ngrams

n = 2
bigrams = count_ngrams(train_data_replaced, n)
print(list(bigrams.items())[:10])

def estimate_probability(word, previous_ngram, ngram_counts, nplus1gram_counts, vocab_size, k=1):
    previous_ngram = tuple(previous_ngram)
    previous_ngram_count = ngram_counts.get(previous_ngram, 0)
    nplus1gram = previous_ngram + (word,)
    nplus1gram_count = nplus1gram_counts.get(nplus1gram, 0)
    probability = (nplus1gram_count + k) / (previous_ngram_count + k * vocab_size)
    return probability

vocab_size = len(closed_vocab) + 1
previous_ngram = ['i', 'eat']
word = 'scrambled'
probability = estimate_probability(word, previous_ngram, bigrams, count_ngrams(train_data_replaced, 3), vocab_size)
print(f"Probability of '{word}' given '{previous_ngram}': {probability}")

def estimate_probabilities(previous_ngram, ngram_counts, nplus1gram_counts, vocab, k=1):
    vocab_size = len(vocab) + 1
    probabilities = {}
    for word in vocab:
        probabilities[word] = estimate_probability(word, previous_ngram, ngram_counts, nplus1gram_counts, vocab_size, k)
    return probabilities

previous_ngram = ['i', 'eat']
vocab = closed_vocab | {'<unk>'}
probabilities = estimate_probabilities(previous_ngram, bigrams, count_ngrams(train_data_replaced, 3), vocab)
print(list(probabilities.items())[:10])

import numpy as np

def calculate_perplexity(sentence, ngram_counts, nplus1gram_counts, vocab_size, k=1):
    sentence = ['<s>'] * (len(ngram_counts) - 1) + sentence + ['<e>']
    N = len(sentence)
    log_prob_sum = 0
    for i in range(len(sentence) - len(ngram_counts) + 1):
        ngram = tuple(sentence[i:i+len(ngram_counts)])
        nplus1gram = tuple(sentence[i:i+len(ngram_counts)+1])
        log_prob_sum += np.log2(estimate_probability(nplus1gram[-1], ngram, ngram_counts, nplus1gram_counts, vocab_size, k))
    perplexity = 2**(-log_prob_sum / N)
    return perplexity

sentence = ['i', 'eat', 'scrambled', 'eggs']
perplexity = calculate_perplexity(sentence, bigrams, count_ngrams(train_data_replaced, 3), vocab_size)
print(f"Perplexity of the sentence '{' '.join(sentence)}': {perplexity}")

def suggest_a_word(previous_tokens, ngram_counts, nplus1gram_counts, vocab, k=1, start_with=None):
    vocab_size = len(vocab) + 1
    probabilities = estimate_probabilities(previous_tokens, ngram_counts, nplus1gram_counts, vocab, k)
    if start_with:
        filtered_probabilities = {word: prob for word, prob in probabilities.items() if word.startswith(start_with)}
    else:
        filtered_probabilities = probabilities
    suggested_word = max(filtered_probabilities, key=filtered_probabilities.get)
    return suggested_word, filtered_probabilities[suggested_word]

previous_tokens = ['i', 'eat', 'scrambled']
suggested_word, max_probability = suggest_a_word(previous_tokens, bigrams, count_ngrams(train_data_replaced, 3), vocab)
print(f"Suggested word: {suggested_word}, Max probability: {max_probability}")

def get_suggestions(previous_tokens, ngram_counts_list, vocab, k=1, start_with=None):
    suggestions = []
    vocab = list(vocab) + ['<unk>']
    for n in range(1, len(ngram_counts_list) + 1):
        ngram_counts = ngram_counts_list[n-1]
        previous_ngram = tuple(previous_tokens[-(n-1):])
        nplus1gram_counts = count_ngrams(train_data_replaced, n+1)
        probabilities = estimate_probabilities(previous_ngram, ngram_counts, nplus1gram_counts, vocab, k)
        for word, prob in probabilities.items():
            if start_with and not word.startswith(start_with):
                continue
            suggestions.append((word, prob))
    suggestions.sort(key=lambda x: x[1], reverse=True)
    return suggestions[:5]

previous_tokens = ['i', 'eat', 'scrambled']
suggestions = get_suggestions(previous_tokens, [count_ngrams(train_data_replaced, n) for n in range(1, 7)], closed_vocab, k=1)
print(f"Suggestions: {suggestions}")

def test_suggestions(previous_tokens, ngram_counts_list, vocab, k=1, top_n=5):
    suggestions = get_suggestions(previous_tokens, ngram_counts_list, vocab, k)
    print(f"Previous tokens: {' '.join(previous_tokens)}")
    print("Top suggestions:")
    for word, prob in suggestions[:top_n]:
        print(f"  {word}: {prob:.4f}")

ngram_counts_list = [count_ngrams(train_data_replaced, n) for n in range(1, 4)]
vocab = closed_vocab | {'<unk>'}

previous_tokens = ['i', 'eat', 'scrambled']
test_suggestions(previous_tokens, ngram_counts_list, vocab, k=1, top_n=5)

test_suggestions(['i', 'love'], ngram_counts_list, vocab, k=1, top_n=5)
test_suggestions(['the', 'quick', 'brown'], ngram_counts_list, vocab, k=1, top_n=5)
test_suggestions(['this', 'is', 'a'], ngram_counts_list, vocab, k=1, top_n=5)
test_suggestions(['can', 'you'], ngram_counts_list, vocab, k=1, top_n=5)

def interactive_test(ngram_counts_list, vocab, k=1, top_n=5):
    print("Interactive Auto-Complete Test. Type 'exit' to quit.")
    while True:
        user_input = input("Enter previous tokens (space-separated): ")
        if user_input.lower() == 'exit':
            break
        previous_tokens = user_input.split()
        test_suggestions(previous_tokens, ngram_counts_list, vocab, k, top_n)

interactive_test(ngram_counts_list, vocab, k=1, top_n=5)


Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
How are you? Btw thanks for the RT. You gonna be in DC anytime soon? Love to see you. Been way, way too long.
When you meet someone special... you'll know. Your heart will beat more rapidly and you'll smile for no reason.
they've decided its more fun if I don't.
So Tired D; Played Lazer Tag & Ran A LOT D; Ughh Going To Sleep Like In 5 Minutes ;)
Words from a complete stranger! Made my birthday even better :)
First Cubs game ever! Wrigley field is gorgeous. This is perfect. Go Cubs Go!
i no! i ge
['How are you? Btw thanks for the RT. You gonna be in DC anytime soon? Love to see you. Been way, way too long.', "When you meet someone special... you'll know. Your heart will beat more rapidly and you'll smile for no reason.", "they've decided its more fun if I don't.", 'So Tired D; Played Lazer Tag & Ran A LOT D; Ughh Going To Sleep Like In 5 Minutes ;)', 'Words fr

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


[['how', 'are', 'you', '?', 'btw', 'thanks', 'for', 'the', 'rt', '.', 'you', 'gon', 'na', 'be', 'in', 'dc', 'anytime', 'soon', '?', 'love', 'to', 'see', 'you', '.', 'been', 'way', ',', 'way', 'too', 'long', '.'], ['when', 'you', 'meet', 'someone', 'special', '...', 'you', "'ll", 'know', '.', 'your', 'heart', 'will', 'beat', 'more', 'rapidly', 'and', 'you', "'ll", 'smile', 'for', 'no', 'reason', '.'], ['they', "'ve", 'decided', 'its', 'more', 'fun', 'if', 'i', 'do', "n't", '.'], ['so', 'tired', 'd', ';', 'played', 'lazer', 'tag', '&', 'ran', 'a', 'lot', 'd', ';', 'ughh', 'going', 'to', 'sleep', 'like', 'in', '5', 'minutes', ';', ')'], ['words', 'from', 'a', 'complete', 'stranger', '!', 'made', 'my', 'birthday', 'even', 'better', ':', ')']]
Train size: 38369, Test size: 9593
[('.', 23617), ('!', 20865), ('the', 15213), ('i', 14796), ('to', 12706), (',', 12272), ('a', 9892), ('you', 9818), ('and', 7082), ('?', 6793)]
Closed vocabulary size: 6834
[['where', 'are', 'you', '<unk>', '?'], ['t

# **References**

Generated Some Functions by Chatgpt

Used some github repositries for guidance

Used https://stackoverflow.com for some functions.


